a="bently"
print(a.startswith('ben'))
print(a.lower())
print(a.endswith('en'))
print(a.count('t'))
print(a.title())
print(a.capitalize())
print(astrip()
print(a.lstrip('b'))
print(a.rstrip*('y'))
print(a.split())
print(a[0]
